adding function existsPath together with test
Phenomics/ontolib pull request #36
Opened 2017-12-14 04:32 UTC by pnrobinson

2017-12-22 08:44 UTC, holtgrewe requested changes
Overall looks good, see inline annotations.

Also, I'd rather have this in algo.OntologyTerms to keep the `Ontology` interfaces slim and rather have utility classes with static functions.

2017-12-22 08:44 UTC, holtgrewe commented on ontolib-core/src/main/java/com/github/phenomics/ontolib/ontology/data/ImmutableOntology.java
> -import java.util.Collection;
Please no star imports but explicit ones. I guess you can easily adjust your IDE to do this.

2017-12-22 08:44 UTC, holtgrewe commented on ontolib-core/src/main/java/com/github/phenomics/ontolib/ontology/data/ImmutableOntology.java
> +    if (sourceID.equals(destID)) return false;
Please wrap and indent consistently. I can send around a style file for Eclipse.

2017-12-22 08:44 UTC, holtgrewe commented on ontolib-core/src/main/java/com/github/phenomics/ontolib/ontology/data/ImmutableOntology.java
> +
Remove superflous whitespace for consistencty.

2017-12-22 08:44 UTC, holtgrewe commented on ontolib-core/src/main/java/com/github/phenomics/ontolib/ontology/data/Ontology.java
> +
Please add javadoc and remove superflous empty lines.

2017-12-22 08:44 UTC, holtgrewe commented on ontolib-core/src/test/java/com/github/phenomics/ontolib/ontology/data/ImmutableOntologyTest.java
> +    assertTrue(ontology.existsPath(id1,id2));
Please make whitespace consistent, your IDE should offer an option to do this automatically.

2017-12-22 08:44 UTC, holtgrewe commented on ontolib-core/src/test/java/com/github/phenomics/ontolib/ontology/data/ImmutableOntologyTest.java
> +
Please remove empty line here and below.

2017-12-22 08:45 UTC, holtgrewe commented on ontolib-core/src/main/java/com/github/phenomics/ontolib/ontology/data/ImmutableOntology.java
> -import java.util.Collection;
Also, I forgot: please add note to Changelog.

2018-01-17 10:56 UTC, pnrobinson commented
I have replaced this PR with PR #39 and will close this

2018-01-17 10:56 UTC, closed without merging